AllCops:
  Exclude:
    - Guardfile
    - bin/**/*
    - vendor/**/*
Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - db/schema.rb
    - db/migrate/**/*.rb
    - lib/tasks/**/*
Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*.rb
Style/StringLiterals:
  Exclude:
    - db/schema.rb
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
