name: api

on:
  pull_request:
    paths:
      - api/**
    branches:
      - master

defaults:
  run:
    working-directory: api/

jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: marker_test
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
          working-directory: api/

      - name: Install gems
        run: bundle install

      - name: Install required apt packages
        run: sudo apt-get -yqq install libpq-dev

      - name: Run linting
        run: bundle exec rubocop --parallel

      - name: Run security checks
        run: |
          bundle exec bundler-audit --update
          bundle exec brakeman -q -w2

      - name: Run tests
        env:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
        run: |
          bin/rails db:setup
          bin/rspec
