name: api

on:
  pull_request:
    paths:
      - api/**
    branches:
      - master

defaults:
  run:
    working-directory: api/

jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: marker
          POSTGRES_DB: marker_test
          POSTGRES_PASSWORD: ""
        ports: ["5432:5432"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run linting
        run: bin/rubocop --parallel

      - name: Run security checks
        run: |
          bin/bundler-audit --update
          bin/brakeman -q -w2

      - name: Run tests
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: marker
        run: |
          bin/rails db:setup
          bin/rspec
