name: api

on:
  pull_request:
    paths:
      - api/**
    branches:
      - master
  push:
    paths:
      - api/**
    branches:
      - master

defaults:
  run:
    working-directory: api/

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
          working-directory: api/

      - name: Install gems
        run: bundle install

      - name: Run rubocop
        run: bundle exec rubocop --parallel

      - name: Run security checks
        run: |
          bundle exec bundler-audit --update
          bundle exec brakeman -q -w2

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: marker_test
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
          working-directory: api/

      - name: Install gems
        run: bundle install

      - name: Install required apt packages
        run: sudo apt-get -yqq install libpq-dev

      - name: Run tests
        env:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          PGPASSWORD: postgres
          RAILS_ENV: test
          web_url: marker.test
        run: |
          bin/rails db:setup
          bin/rspec

  deploy:
    name: Deploy to prod
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: markerapi
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: api

